// Generated by Web team via dj_dispatch (Ship 77)
// Do not edit by hand — re-run R&D audit + dispatch to refresh.

export const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "name": "crestair",
  "url": "https://crestairaz.com"
};

export const schemaJsonLdScript = `<script type="application/ld+json">${JSON.stringify(localBusinessSchema)}</script>`;
